name       : libxv
version    : 1.0.11
release    : 7
source     :
    - https://www.x.org/releases/individual/lib/libXv-1.0.11.tar.gz : c4112532889b210e21cf05f46f0f2f8354ff7e1b58061e12d7a76c95c0d47bb1
license    : GPL-3.0+
summary    : X11 Video extension library
component  : xorg.library
builddeps  :
    - pkgconfig(videoproto)
    - pkgconfig(xext)
    - pkgconfig32(xext)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
optimize   : speed
patterns   :
    - devel : /usr/share/man
description: |
    libXv provides an X Window System client interface to the XVideo extension to the X protocol.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
