name        : libxv
version     : 1.0.10
release     : 6
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libXv-1.0.10.tar.bz2 : 55fe92f8686ce8612e2c1bfaf58c057715534419da700bda8d517b1d97914525
license     : GPL-3.0+
summary     : X11 Video extension library
component   : xorg.library
builddeps   :
    - pkgconfig(videoproto)
    - pkgconfig(xext)
    - pkgconfig32(xext)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
optimize    : speed
patterns    :
    - devel: /usr/share/man
description : |
    libXv provides an X Window System client interface to the XVideo extension to the X protocol.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
