name       : libxv
version    : 1.0.11
release    : 12
source     :
    - https://www.x.org/releases/individual/lib/libXv-1.0.11.tar.gz : c4112532889b210e21cf05f46f0f2f8354ff7e1b58061e12d7a76c95c0d47bb1
license    : MIT
summary    : X11 Video extension library
component  : xorg.library
description: |
    libXv provides an X Window System client interface to the XVideo extension to the X protocol.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(xext)
    - pkgconfig32(x11)
    - pkgconfig(xproto)
patterns   :
    - devel : /usr/share/man
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
